test-variable := "0.2.7"

# List all recipies
default:
    just --list --color never

# Build command
build-cmd version='0.4':
    echo {{version}}

# Terraform plan
plan:
    echo "planner"

@push version: (build-cmd version)
    echo {{version}}

push2 version1 version2:
    echo {{version1}} {{version2}}

# A target that will fail
fail:
    exit 1
