* 0.4

- Provides explicit details once just recipe execution is
  completed. This is what you used to appear before:

#+begin_example sh
echo "planner"
planner
#+end_example

This is what appears now:

#+begin_example sh
echo "planner"
planner

Finished execution: exit-code 0
#+end_example

This is useful for two reasons: When a huge amount of output is being
produced from a just target, we know exactly when the process has
finished and what it's exit status code looks like.

- Better error handling when you have error in your just file.

* 0.3

- Add ability to turn off color in the output. Useful for eshell
  integration which doesn't recognize color without additional setup.

- Integration with eshell done. You can now execute the recipies in
  either eshell or open eshell and give positional arguments etc for
  the recipe before executing it. The key binding for it is *E* and
  *W*.

- Handle recipe names starting with /@/

- Add *justl-go-to-recipe* function which will take you to the
  justfile where the recipe under the cursor is present. It's default
  key binding is *RET*

- Change behaviour of executing recipes. It now reads the recipe to
  see if it has any input parameters and asks the value explicitly
  along with some smart behavior for default values. Eg:

#+begin_example just
push2 version1 version2:
    echo {{version1}} {{version2}}
#+end_example

It will ask the values for both version1 and version2 explicitly in
the above case.

- Implement *justl--exec-recipe-with-args* to provide explicit
  arguments to it. It's shortcut in *justl* buffer is *w*.

* 0.2

- Address various comments from the melpa maintainers.
- Use sharp quotes *#'* to provide hints to the byte compiler which
  will warn if the function is undefined.

* 0.1

- Initial version released
