* 0.10

- Integrate compilation mode for ~justl-exec-recipe-in-dir~
- Fix documentation in README.

* 0.9

- Handle carriage return properly on the compilation buffer.

* 0.8

- Define a compilation mode named ~justl-compile-mode~. Executing
  ~justl-exec-recipe~ (which is bind to the keybinding ~e~ in the
  transient buffer) which show results in this mode.
- Don't output at the bottom of the screen if the just target
  execution fails. Instead, it's displayed in the compilation mode
  now.
- Use font locking to hightlight the execution status of just target.
- Make the ~*just-process*~ buffer as read only. This prevents from
  un-intentional edits when viewing the logs.
- Use the variable ~justl-executable~ instead of hardcoding the string
  ~just~ everywhere.
- Update CI to test for 28.1 Emacs. Remove other old version from the
  check matrix.

* 0.7

- Finds all types of justfiles now and makes it compatible with the
  ~just~ program. Earlier it used to just working with ~justfile~ and
  ~.justfile~.

* 0.6

- Make the directory parsing smart. Now invoking justl from any
  subdirectory should work.
- eshell executes from the directory where justfile is placed.
- Introduce buffer local variable ~justl--justfile~ which contains
  the justfile location for a particular justl-mode buffer.

* 0.5

- Stop following symbolic link as it leads to a high CPU usage. This
  situation can happen frequently in a distribution like NixOS where
  you can have a symbolic link inside nix's store ~/nix/store~.
- Minor cleanup in the way logging happens in the ~just-process~
  buffer.
- Fix bug when process execution itself throws error.
- Migrate from the deprecated ~define-transient-command~
- Fix justl process when you pass transient argument for ~--color~

* 0.4

- Provides explicit details once just recipe execution is
  completed. This is what you used to appear before:

#+begin_example sh
echo "planner"
planner
#+end_example

This is what appears now:

#+begin_example sh
echo "planner"
planner

Finished execution: exit-code 0
#+end_example

This is useful for two reasons: When a huge amount of output is being
produced from a just target, we know exactly when the process has
finished and what it's exit status code looks like.

- Better error handling when you have error in your just file.

* 0.3

- Add ability to turn off color in the output. Useful for eshell
  integration which doesn't recognize color without additional setup.

- Integration with eshell done. You can now execute the recipies in
  either eshell or open eshell and give positional arguments etc for
  the recipe before executing it. The key binding for it is *E* and
  *W*.

- Handle recipe names starting with /@/

- Add *justl-go-to-recipe* function which will take you to the
  justfile where the recipe under the cursor is present. It's default
  key binding is *RET*

- Change behaviour of executing recipes. It now reads the recipe to
  see if it has any input parameters and asks the value explicitly
  along with some smart behavior for default values. Eg:

#+begin_example just
push2 version1 version2:
    echo {{version1}} {{version2}}
#+end_example

It will ask the values for both version1 and version2 explicitly in
the above case.

- Implement *justl--exec-recipe-with-args* to provide explicit
  arguments to it. It's shortcut in *justl* buffer is *w*.

* 0.2

- Address various comments from the melpa maintainers.
- Use sharp quotes *#'* to provide hints to the byte compiler which
  will warn if the function is undefined.

* 0.1

- Initial version released
